export enum ChatEvents {
    Message = 'message',
    Validate = 'validate',
    BroadcastAll = 'broadcastAll',
    JoinRoom = 'joinRoom',
    RoomMessage = 'roomMessage',
    JoinedRoom = 'test',
    ClickValidation = 'clickValidation',
    CreateRoom = 'createRoom',
    Found = 'found',
    NoRoom = 'noRoom',
    CongratMessage = 'congratMessage',
    WordValidated = 'wordValidated',
    MassMessage = 'massMessage',
    Hello = 'hello',
    Clock = 'clock',
    ClickValidated = 'clickValidated',
    RoomCreated = 'roomCreated',
    JoinGridRoom = 'joinGridRoom',
    Hint = 'hint',
}
