export enum ChatEvents {
    Message = 'message',
    Validate = 'validate',
    BroadcastAll = 'broadcastAll',
    JoinRoom = 'joinRoom',
    RoomMessage = 'roomMessage',
    JoinedRoom = 'joinedRoom',
    ClickValidation = 'clickValidation',
    Found = 'found',
    CongratMessage = 'congratMessage',
    WordValidated = 'wordValidated',
    MassMessage = 'massMessage',
    Hello = 'hello',
    Clock = 'clock',
    ClickValidated = 'clickValidated',
}
